name: ${project.name}
main: sk.perri.kc.vote.Main
version: ${project.version}
author: Perri
softdepend: [MVdWPlaceholderAPI, HolographicDisplays]
description: ${project.description}
commands:
  vote:
    aliases: [hlasuj]
  hlasy:
    aliases: [votes]
  voteparty:
    aliases: [vp]
  fakevote:
  offlinevote:
    aliases: [offvote,ofv]
  voteinfo: